In [2]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("bank-additional-full.csv")

df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56.0,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57.0,services,married,high.school,unknown,no,no,telephone,may,mon,...,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37.0,services,married,high.school,no,yes,no,telephone,may,mon,...,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40.0,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56.0,services,married,high.school,no,no,yes,telephone,may,mon,...,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [6]:
df.shape

(41188, 21)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41176 non-null  float64
 1   job             41176 non-null  object
 2   marital         41176 non-null  object
 3   education       41176 non-null  object
 4   default         41176 non-null  object
 5   housing         41176 non-null  object
 6   loan            41176 non-null  object
 7   contact         41176 non-null  object
 8   month           41176 non-null  object
 9   day_of_week     41176 non-null  object
 10  duration        41176 non-null  float64
 11  campaign        41176 non-null  float64
 12  pdays           41176 non-null  float64
 13  previous        41176 non-null  float64
 14  poutcome        41176 non-null  object
 15  emp.var.rate    41176 non-null  float64
 16  cons.price.idx  41176 non-null  float64
 17  cons.conf.idx   41176 non-null  float64
 18  euribor3m       41176 non-null  float64
 19  nr.employed     41176 non-null  float64
 20  y               41176 non-null  object
dtypes: float64(10), object(11)
memory usage: 6.6+ MB

In [8]:
df.describe()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
count,41176.00000,41176.000000,41176.000000,41176.000000,41176.000000,41176.000000,41176.000000,41176.000000,41176.000000,41176.000000
mean,40.02380,258.315815,2.567879,962.464810,0.173013,0.081922,93.575720,-40.502863,3.621293,5167.034870
std,10.42068,259.305321,2.770318,186.937102,0.494964,1.570883,0.578839,4.627860,1.734437,72.251364
min,17.00000,0.000000,1.000000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000
25%,32.00000,102.000000,1.000000,999.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000
50%,38.00000,180.000000,2.000000,999.000000,0.000000,1.100000,93.749000,-41.800000,4.857000,5191.000000
75%,47.00000,319.000000,3.000000,999.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000
max,98.00000,4918.000000,56.000000,999.000000,7.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000

In [9]:
df['y'].value_counts()

y
no     36537
yes     4639
Name: count, dtype: int64

In [11]:
df['y'].value_counts(normalize=True) #Campaign_Succes_Rate

y
no     0.887337
yes    0.112663
Name: proportion, dtype: float64

In [16]:
#Job Distribution
df['job'].value_counts()

job
admin.           10419
blue-collar       9253
technician        6739
services          3967
management        2924
retired           1718
entrepreneur      1456
self-employed     1421
housemaid         1060
unemployed        1014
student            875
unknown            330
Name: count, dtype: int64

In [14]:
#Marital Status
df['marital'].value_counts()

marital
married     24921
single      11564
divorced     4611
unknown        80
Name: count, dtype: int64

In [15]:
#Education
df['education'].value_counts()

education
university.degree      12164
high.school             9512
basic.9y                6045
professional.course     5240
basic.4y                4176
basic.6y                2291
unknown                 1730
illiterate                18
Name: count, dtype: int64

In [17]:
df['campaign'].mean()

np.float64(2.567879347192539)

In [20]:
df.groupby('month')['y'].value_counts() #Campaign success by month

month  y
apr    no      2092
       yes      539
aug    no      5521
       yes      655
dec    no        93
       yes       89
jul    no      6521
       yes      648
jun    no      4759
       yes      559
mar    yes      276
       no       270
may    no     12881
       yes      886
nov    no      3684
       yes      416
oct    no       402
       yes      315
sep    no       314
       yes      256
Name: count, dtype: int64

In [21]:
df.groupby('job')['duration'].mean()

job
admin.           254.315961
blue-collar      264.557549
entrepreneur     263.267857
housemaid        250.454717
management       257.058140
retired          273.909779
self-employed    264.142153
services         258.491303
student          283.683429
technician       250.287431
unemployed       249.451677
unknown          239.675758
Name: duration, dtype: float64

In [22]:
df.groupby('job')['campaign'].mean()

job
admin.           2.623572
blue-collar      2.558630
entrepreneur     2.535714
housemaid        2.639623
management       2.476060
retired          2.478463
self-employed    2.660802
services         2.588606
student          2.104000
technician       2.577831
unemployed       2.564103
unknown          2.648485
Name: campaign, dtype: float64

In [23]:
#from notebook to GCP BigQuery
!pip install pandas-gbq

Collecting pandas-gbq
  Downloading pandas_gbq-0.34.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: setuptools in c:\users\bharat vats\anaconda3\lib\site-packages (from pandas-gbq) (72.1.0)
Collecting db-dtypes<2.0.0,>=1.0.4 (from pandas-gbq)
  Downloading db_dtypes-1.5.0-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: numpy>=1.18.1 in c:\users\bharat vats\anaconda3\lib\site-packages (from pandas-gbq) (2.1.3)
Requirement already satisfied: pandas>=1.1.4 in c:\users\bharat vats\anaconda3\lib\site-packages (from pandas-gbq) (2.2.3)
Requirement already satisfied: pyarrow>=4.0.0 in c:\users\bharat vats\anaconda3\lib\site-packages (from pandas-gbq) (19.0.0)
Collecting pydata-google-auth>=1.5.0 (from pandas-gbq)
  Downloading pydata_google_auth-1.9.1-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting psutil>=5.9.8 (from pandas-gbq)
  Downloading psutil-7.2.2-cp37-abi3-win_amd64.whl.metadata (22 kB)
Collecting google-api-core<3.0.0,>=2.15.0 (from pandas-gbq)
  Downloading google_api_core-2.30.0-py3-none-any.whl.metadata (3.1 kB)
Collecting google-auth>=2.14.1 (from pandas-gbq)
  Downloading google_auth-2.49.1-py3-none-any.whl.metadata (6.2 kB)
Collecting google-auth-oauthlib>=0.7.0 (from pandas-gbq)
  Downloading google_auth_oauthlib-1.3.0-py3-none-any.whl.metadata (2.9 kB)
Collecting google-cloud-bigquery<4.0.0,>=3.20.0 (from pandas-gbq)
  Downloading google_cloud_bigquery-3.40.1-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: packaging>=22.0.0 in c:\users\bharat vats\anaconda3\lib\site-packages (from pandas-gbq) (24.2)
Collecting googleapis-common-protos<2.0.0,>=1.56.3 (from google-api-core<3.0.0,>=2.15.0->pandas-gbq)
  Downloading googleapis_common_protos-1.73.0-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: protobuf<7.0.0,>=4.25.8 in c:\users\bharat vats\anaconda3\lib\site-packages (from google-api-core<3.0.0,>=2.15.0->pandas-gbq) (5.29.3)
Collecting proto-plus<2.0.0,>=1.22.3 (from google-api-core<3.0.0,>=2.15.0->pandas-gbq)
  Downloading proto_plus-1.27.1-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in c:\users\bharat vats\anaconda3\lib\site-packages (from google-api-core<3.0.0,>=2.15.0->pandas-gbq) (2.32.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\bharat vats\anaconda3\lib\site-packages (from google-auth>=2.14.1->pandas-gbq) (0.2.8)
Requirement already satisfied: cryptography>=38.0.3 in c:\users\bharat vats\anaconda3\lib\site-packages (from google-auth>=2.14.1->pandas-gbq) (44.0.1)
Collecting google-cloud-core<3.0.0,>=2.4.1 (from google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq)
  Downloading google_cloud_core-2.5.0-py3-none-any.whl.metadata (3.1 kB)
Collecting google-resumable-media<3.0.0,>=2.0.0 (from google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq)
  Downloading google_resumable_media-2.8.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in c:\users\bharat vats\anaconda3\lib\site-packages (from google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (2.9.0.post0)
Collecting grpcio<2.0.0,>=1.33.2 (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq)
  Downloading grpcio-1.78.0-cp313-cp313-win_amd64.whl.metadata (3.9 kB)
Collecting grpcio-status<2.0.0,>=1.33.2 (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq)
  Downloading grpcio_status-1.78.0-py3-none-any.whl.metadata (1.3 kB)
Collecting google-crc32c<2.0.0,>=1.0.0 (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq)
  Downloading google_crc32c-1.8.0-cp313-cp313-win_amd64.whl.metadata (1.8 kB)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\bharat vats\anaconda3\lib\site-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (4.12.2)
Collecting protobuf<7.0.0,>=4.25.8 (from google-api-core<3.0.0,>=2.15.0->pandas-gbq)
  Downloading protobuf-6.33.5-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Requirement already satisfied: pytz>=2020.1 in c:\users\bharat vats\anaconda3\lib\site-packages (from pandas>=1.1.4->pandas-gbq) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\bharat vats\anaconda3\lib\site-packages (from pandas>=1.1.4->pandas-gbq) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\bharat vats\anaconda3\lib\site-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\bharat vats\anaconda3\lib\site-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.15.0->pandas-gbq) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\bharat vats\anaconda3\lib\site-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.15.0->pandas-gbq) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\bharat vats\anaconda3\lib\site-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.15.0->pandas-gbq) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\bharat vats\anaconda3\lib\site-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.15.0->pandas-gbq) (2025.4.26)
Requirement already satisfied: cffi>=1.12 in c:\users\bharat vats\anaconda3\lib\site-packages (from cryptography>=38.0.3->google-auth>=2.14.1->pandas-gbq) (1.17.1)
Requirement already satisfied: pycparser in c:\users\bharat vats\anaconda3\lib\site-packages (from cffi>=1.12->cryptography>=38.0.3->google-auth>=2.14.1->pandas-gbq) (2.21)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib>=0.7.0->pandas-gbq)
  Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\bharat vats\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.14.1->pandas-gbq) (0.4.8)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq)
  Downloading oauthlib-3.3.1-py3-none-any.whl.metadata (7.9 kB)
Downloading pandas_gbq-0.34.0-py3-none-any.whl (50 kB)
Downloading db_dtypes-1.5.0-py3-none-any.whl (18 kB)
Downloading google_api_core-2.30.0-py3-none-any.whl (173 kB)
Downloading google_auth-2.49.1-py3-none-any.whl (240 kB)
Downloading google_cloud_bigquery-3.40.1-py3-none-any.whl (262 kB)
Downloading google_cloud_core-2.5.0-py3-none-any.whl (29 kB)
Downloading google_resumable_media-2.8.0-py3-none-any.whl (81 kB)
Downloading google_crc32c-1.8.0-cp313-cp313-win_amd64.whl (34 kB)
Downloading googleapis_common_protos-1.73.0-py3-none-any.whl (297 kB)
Downloading grpcio-1.78.0-cp313-cp313-win_amd64.whl (4.8 MB)
   ---------------------------------------- 0.0/4.8 MB ? eta -:--:--
   ---------- ----------------------------- 1.3/4.8 MB 6.7 MB/s eta 0:00:01
   ---------------------------- ----------- 3.4/4.8 MB 8.3 MB/s eta 0:00:01
   ---------------------------------------- 4.8/4.8 MB 8.5 MB/s eta 0:00:00
Downloading grpcio_status-1.78.0-py3-none-any.whl (14 kB)
Downloading proto_plus-1.27.1-py3-none-any.whl (50 kB)
Downloading protobuf-6.33.5-cp310-abi3-win_amd64.whl (437 kB)
Downloading google_auth_oauthlib-1.3.0-py3-none-any.whl (19 kB)
Downloading psutil-7.2.2-cp37-abi3-win_amd64.whl (137 kB)
Downloading pydata_google_auth-1.9.1-py2.py3-none-any.whl (15 kB)
Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
Downloading oauthlib-3.3.1-py3-none-any.whl (160 kB)
Installing collected packages: psutil, protobuf, oauthlib, grpcio, google-crc32c, requests-oauthlib, proto-plus, googleapis-common-protos, google-resumable-media, grpcio-status, google-auth, db-dtypes, google-auth-oauthlib, google-api-core, pydata-google-auth, google-cloud-core, google-cloud-bigquery, pandas-gbq

  Attempting uninstall: psutil

    Found existing installation: psutil 5.9.0

    Uninstalling psutil-5.9.0:

      Successfully uninstalled psutil-5.9.0

   ----------------------------------------  0/18 [psutil]
   ----------------------------------------  0/18 [psutil]
  Attempting uninstall: protobuf
   ----------------------------------------  0/18 [psutil]
    Found existing installation: protobuf 5.29.3
   ----------------------------------------  0/18 [psutil]
    Uninstalling protobuf-5.29.3:
   ----------------------------------------  0/18 [psutil]
      Successfully uninstalled protobuf-5.29.3
   ----------------------------------------  0/18 [psutil]
   -- -------------------------------------  1/18 [protobuf]
   -- -------------------------------------  1/18 [protobuf]
   -- -------------------------------------  1/18 [protobuf]
   -- -------------------------------------  1/18 [protobuf]
   -- -------------------------------------  1/18 [protobuf]
   ---- -----------------------------------  2/18 [oauthlib]
   ---- -----------------------------------  2/18 [oauthlib]
   ---- -----------------------------------  2/18 [oauthlib]
   ------ ---------------------------------  3/18 [grpcio]
   ------ ---------------------------------  3/18 [grpcio]
   ------ ---------------------------------  3/18 [grpcio]
   ------ ---------------------------------  3/18 [grpcio]
   ----------- ----------------------------  5/18 [requests-oauthlib]
   ------------- --------------------------  6/18 [proto-plus]
   --------------- ------------------------  7/18 [googleapis-common-protos]
   --------------- ------------------------  7/18 [googleapis-common-protos]
   --------------- ------------------------  7/18 [googleapis-common-protos]
   --------------- ------------------------  7/18 [googleapis-common-protos]
   --------------- ------------------------  7/18 [googleapis-common-protos]
   ----------------- ----------------------  8/18 [google-resumable-media]
   -------------------- -------------------  9/18 [grpcio-status]
   ---------------------- ----------------- 10/18 [google-auth]
   ---------------------- ----------------- 10/18 [google-auth]
   ---------------------- ----------------- 10/18 [google-auth]
   ---------------------- ----------------- 10/18 [google-auth]
   -------------------------- ------------- 12/18 [google-auth-oauthlib]
   ---------------------------- ----------- 13/18 [google-api-core]
   ---------------------------- ----------- 13/18 [google-api-core]
   ---------------------------- ----------- 13/18 [google-api-core]
   ------------------------------- -------- 14/18 [pydata-google-auth]
   --------------------------------- ------ 15/18 [google-cloud-core]
   ----------------------------------- ---- 16/18 [google-cloud-bigquery]
   ----------------------------------- ---- 16/18 [google-cloud-bigquery]
   ----------------------------------- ---- 16/18 [google-cloud-bigquery]
   ------------------------------------- -- 17/18 [pandas-gbq]
   ---------------------------------------- 18/18 [pandas-gbq]

Successfully installed db-dtypes-1.5.0 google-api-core-2.30.0 google-auth-2.49.1 google-auth-oauthlib-1.3.0 google-cloud-bigquery-3.40.1 google-cloud-core-2.5.0 google-crc32c-1.8.0 google-resumable-media-2.8.0 googleapis-common-protos-1.73.0 grpcio-1.78.0 grpcio-status-1.78.0 oauthlib-3.3.1 pandas-gbq-0.34.0 proto-plus-1.27.1 protobuf-6.33.5 psutil-7.2.2 pydata-google-auth-1.9.1 requests-oauthlib-2.0.0

In [25]:
from pandas_gbq import to_gbq

In [26]:
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56.0,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57.0,services,married,high.school,unknown,no,no,telephone,may,mon,...,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37.0,services,married,high.school,no,yes,no,telephone,may,mon,...,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40.0,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56.0,services,married,high.school,no,no,yes,telephone,may,mon,...,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [28]:
project_id = "retail-banking-490411"
table_id = "retail_banking_dataset.banking_table"

In [29]:
to_gbq(df, table_id, project_id=project_id, if_exists="replace")

Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=262006177488-3425ks60hkk80fssi9vpohv88g6q1iqd.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fbigquery&state=4lMwcWTebSMifsTA4511VtFGXvpza5&code_challenge=qXwwU5RUM8N3TeNbJNRrsMYOFU-z6CYe2BhgPgFuhys&code_challenge_method=S256&prompt=consent&access_type=offline

GenericGBQException: Reason: 400 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/retail-banking-490411/jobs?uploadType=multipart: Invalid field name "emp.var.rate". Fields must contain the allowed characters, and be at most 300 characters long. For allowed characters, please refer to https://cloud.google.com/bigquery/docs/schemas#column_names

In [30]:
df.columns = df.columns.str.replace('.', '_', regex=False)

In [31]:
print(df.columns)

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp_var_rate', 'cons_price_idx',
       'cons_conf_idx', 'euribor3m', 'nr_employed', 'y'],
      dtype='object')

In [32]:
from pandas_gbq import to_gbq

project_id = "retail-banking-490411"
table_id = "retail_banking_dataset.banking_table"

to_gbq(df, table_id, project_id=project_id, if_exists="replace")

100%|██████████| 1/1 [00:00<00:00, 7476.48it/s]